<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Wskazanie manifestu administratora -->
    <ApplicationManifest>app.manifest</ApplicationManifest>
    
    <!-- Podpięcie ikony programu -->
    <ApplicationIcon>app.ico</ApplicationIcon>

    <!-- Automatyczne pakowanie do 1 pliku .exe -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    
    <!-- Dane o wersji pliku -->
    <Version>1.0.0</Version>
    <Authors>pro100wpysk</Authors>
    <Product>TurboSuiteApex</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="*" />
  </ItemGroup>

</Project>